# Generated by Django 3.1.7 on 2021-03-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_title', models.CharField(max_length=100, verbose_name='狗狗标题')),
                ('salesLocation', models.CharField(max_length=100, verbose_name='售卖地址')),
                ('dog_breed', models.CharField(max_length=50, verbose_name='狗狗品种')),
                ('dog_age', models.CharField(max_length=50, verbose_name='狗狗年龄')),
                ('vaccineSituation', models.CharField(max_length=50, verbose_name='疫苗情况')),
                ('publisher', models.CharField(max_length=50, verbose_name='发布人')),
                ('dog_price', models.CharField(max_length=20, verbose_name='狗狗价格')),
                ('sellerPromise', models.CharField(max_length=200, verbose_name='卖家承诺')),
                ('dog_detailedInterface', models.CharField(max_length=200, verbose_name='详情页面')),
            ],
        ),
    ]
